# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'hostgroups',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Hostgroup'),
        ),
    ]
