# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostgroup',
            field=models.ManyToManyField(to='core.Hostgroup'),
        ),
    ]
