# Generated by Django 2.2.4 on 2019-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostFacts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facts', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'host_facts',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='facts',
            field=models.ManyToManyField(to='core.HostFacts'),
        ),
    ]
