# Generated by Django 2.2.4 on 2019-08-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190807_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostfacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
