# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181107_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='hostgroup',
        ),
        migrations.AddField(
            model_name='host',
            name='groups',
            field=models.ManyToManyField(to='core.Hostgroup'),
        ),
    ]
