# Generated by Django 2.2.4 on 2019-08-07 16:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190807_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostfacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 7, 16, 25, 31, 226290, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
