# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_host_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Host is rechable')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last checked')),
            ],
            options={
                'db_table': 'hoststatus',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.HostStatus'),
        ),
    ]
