# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181115_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.HostStatus'),
        ),
    ]
