# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181115_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Host is rechable'),
        ),
    ]
