# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181115_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='status',
            new_name='active',
        ),
    ]
