# Generated by Django 2.2.5 on 2019-09-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networks_subnet_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='networks',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
